name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ""  

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: username / Discord ID
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: jot down the details of what happened and what should have happened?
      placeholder: write your step by step treasure map here!
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Show us what happened
      description: post your best screenshot of your bug
      placeholder: drag & drop your screenshot here
    validations:
      required: false
  - type: textarea
    id: repro
    attributes:
      label: Tell us how this happened
      description: write a step by step sequence of your actions
      placeholder: "" 
    validations:
      required: true

