blank_issues_enabled: false
contact_links:
  - name: Menyr Support
    url: https://github.com/NOGStudio/Menyr-Feedback
    about: Please post and follows bugs here.
  - name: Menyr Roadmap
    url: https://portal.productboard.com/ycntuexygoaukq1vqftharus/tabs/4-roadmap
    about: Please ppropose and follow knew features here.